// <auto-generated />
using Nexa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nexa.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603120000_AddFarmaciaCensoDispatch")]
    partial class AddFarmaciaCensoDispatch
    {
    }
}
